/* v140 每位角色的招牌動畫（MOTIF）：每次出招都會出現該角色的招牌元素，奧義時規模更大。
   例：路飛橡膠拳影、索隆阿修羅鬼影、艾斯火拳、青雉冰原、艾涅爾雷鼓、羅的 ROOM、漢庫克愛心、多佛朗明哥鳥籠、
   馬爾科不死鳥、凱多青龍、美音音符、莫莉亞蝙蝠、卡塔庫栗年糕、黃猿光束、赤犬岩漿拳、BIG MOM 太陽雲……
   與技能特效共用開關 op_fxpro（低＝不顯示）。 */
const MOTIF = {
  luffy0: 'rubber', nami: 'clima', luffy: 'rubber', luffy_nika: 'nika', zoro: 'asura', sanji: 'kick', robin: 'hands', franky: 'robo', brook: 'notes', jinbe: 'waterfist',
  coby0: 'fist', morgan: 'axe', marine: 'fist', koby_mf: 'fist', garp_mf: 'meteor', garp_hc: 'meteor', koby_hc: 'fist', akainu: 'magma', aokiji: 'icefield', kizaru: 'beams',
  magellan: 'hydra', lucci: 'claws', vergo: 'bamboo', mihawk: 'greenslash', mihawk_w: 'greenslash', crocodile: 'sandspiral', doflamingo: 'birdcage', kuma: 'paws', kuma_eh: 'paws',
  moria: 'bats', law: 'room', law_w: 'room', hancock: 'hearts', weevil: 'axe', blackbeard_w: 'blackhole', blackbeard: 'blackhole', ace: 'firefist', marco: 'phoenix',
  uta: 'notes', king: 'pteranodon', katakuri: 'mochi', catarina: 'foxfire', burgess: 'meteor', vasco: 'firefist', shanks: 'kingsaura', roger: 'kingsaura', buggy: 'parts',
  whitebeard: 'crack', bigmom: 'homies', kaido: 'dragon', makino: 'notes', mayor: 'fist', lordcoast: 'hydra', vivi: 'waterfist', koza: 'fist', enel: 'drums', wiper: 'meteor',
  perona: 'ghosts', hody: 'sharks', shirahoshi: 'seakings', monet: 'snow', sugar: 'toys', kid: 'magnet', kinemon: 'foxfire', tama: 'fist', yamato: 'icefield', vegapunk: 'beams',
  york: 'beams', morgans: 'claws', loki: 'drums', dorry: 'giantblade', brogy: 'giantblade', rocks: 'kingsaura', imu: 'blackhole'
};
(function () {
  const on = () => window.FXPRO && FXPRO.on();
  const $ = id => document.getElementById(id);
  const R = (a, b) => a + Math.random() * (b - a), TAU = Math.PI * 2, LOW = typeof LOWFX !== 'undefined' && LOWFX;
  const n = k => Math.max(1, Math.round(k * (LOW ? .6 : 1)));
  const add = o => FXE.add(o), P = () => FXE.P;
  const later = (ms, f) => setTimeout(() => { try { f(); } catch (e) { } }, ms / (window.BSPEED || 1));
  const fade = (k, a, b) => k < a ? k / a : k > b ? Math.max(0, (1 - k) / (1 - b)) : 1;
  function heart(c, s) { c.beginPath(); c.moveTo(0, s * .3); c.bezierCurveTo(-s, -s * .4, -s * .4, -s * 1.1, 0, -s * .45); c.bezierCurveTo(s * .4, -s * 1.1, s, -s * .4, 0, s * .3); c.fill(); }
  function fist(c, s, col) { c.fillStyle = col; c.beginPath(); c.ellipse(0, 0, s, s * .8, 0, 0, TAU); c.fill(); c.fillStyle = 'rgba(0,0,0,.25)'; for (let i = 0; i < 4; i++) { c.beginPath(); c.ellipse(s * .55, -s * .5 + i * s * .34, s * .2, s * .14, 0, 0, TAU); c.fill(); } }
  /* 投射物：從施放者飛到目標 */
  function fly(A, draw, o) { o = o || {}; const life = o.life || .45; add({ add: o.add !== false, life, draw(c, k) { const e = o.ease ? o.ease(k) : 1 - Math.pow(1 - k, 2), x = A.f.x + (A.t.x - A.f.x) * e, y = A.f.y + (A.t.y - A.f.y) * e - Math.sin(k * Math.PI) * (o.arc || 0); c.globalAlpha = fade(k, .05, .9); c.translate(x, y); if (A.d < 0) c.scale(-1, 1); draw(c, k); } }); }
  function fwings(x, y, cols, life, sc) { add({ add: true, life, draw(c, k, dt, t) { c.globalAlpha = fade(k, .12, .75); const flap = Math.sin(t * 10) * .3; [-1, 1].forEach(sd => { for (let i = 0; i < 7; i++) { const a = -Math.PI / 2 + sd * (.5 + i * .17 + flap), L = (110 + i * 22) * sc, g = c.createLinearGradient(x, y, x + Math.cos(a) * L, y + Math.sin(a) * L); g.addColorStop(0, cols[0]); g.addColorStop(.5, cols[1]); g.addColorStop(1, 'rgba(0,0,0,0)'); c.strokeStyle = g; c.lineWidth = (18 - i * 1.5) * sc; c.lineCap = 'round'; c.beginPath(); c.moveTo(x, y); c.quadraticCurveTo(x + Math.cos(a - sd * .3) * L * .6, y + Math.sin(a - sd * .3) * L * .6, x + Math.cos(a) * L, y + Math.sin(a) * L); c.stroke(); } }); } }); }
  const M = {
    rubber(A, big) { for (let i = 0; i < (big ? 8 : 3); i++) later(i * 70, () => fly({ ...A, t: { x: A.t.x, y: A.t.y + R(-50, 40) } }, (c, k) => { c.save(); c.scale(1 + k * .6, 1 + k * .6); fist(c, big ? 34 : 24, '#f0b98a'); c.restore(); c.strokeStyle = 'rgba(255,255,255,.7)'; c.lineWidth = 2; for (let j = 0; j < 3; j++) { c.beginPath(); c.moveTo(-40 - j * 14, -12 + j * 12); c.lineTo(-90 - j * 14, -12 + j * 12); c.stroke(); } }, { life: .3, add: false })); },
    nika(A, big) { P().rays(A.f.x, A.f.y - 40, { r: big ? 520 : 320, life: 1.2 }); for (let i = 0; i < n(big ? 30 : 14); i++) later(i * 30, () => P().text(A.f.x + R(-140, 140), A.f.y + R(-160, 40), '咚', { size: R(26, 44), life: .7, color: '#ffffff', color2: '#ffe08a', rot: R(-.4, .4) })); },
    asura(A, big) { const ghosts = big ? 3 : 1; for (let g = 0; g < ghosts; g++) add({ life: 1.1, draw(c, k) { c.globalAlpha = fade(k, .15, .6) * .55; c.translate(A.f.x + A.d * (g - 1) * 50, A.f.y - 30 - g * 10); c.scale(1.4 + g * .1, 1.4 + g * .1); c.fillStyle = '#1a3a2a'; c.shadowColor = '#3adf8a'; c.shadowBlur = 30; c.beginPath(); c.ellipse(0, -60, 34, 42, 0, 0, TAU); c.fill(); c.fillStyle = '#ff3a3a'; c.beginPath(); c.arc(-12, -66, 5, 0, TAU); c.arc(12, -66, 5, 0, TAU); c.fill(); } });
      for (let i = 0; i < (big ? 9 : 3); i++) later(200 + i * 80, () => P().slash(A.t.x + R(-30, 30), A.t.y + R(-40, 30), { r: 150, a: R(-3, 0), span: 2, color: '#c8ffd8', w: 14, life: .3 })); },
    kick(A, big) { for (let i = 0; i < (big ? 6 : 3); i++) later(i * 90, () => P().crescent(A.f.x, A.f.y + 20, A.t.x, A.t.y + R(-40, 40), { color: big ? '#8fd8ff' : '#ffb04a', life: .35 })); },
    hands(A, big) { P().hands(A.t.x, A.t.y, { n: big ? 24 : 10 }); P().particles({ x: A.t.x, y: A.t.y, n: big ? 40 : 18, spd: [80, 260], life: [.6, 1], size: [4, 8], colors: ['#ff8ad8', '#ffd0f0', '#ffffff'], drag: 2 }); },
    robo(A, big) { P().beam(A.f.x + A.d * 40, A.f.y - 20, A.t.x, A.t.y, { c2: '#5ad8ff', w: big ? 50 : 26, life: .6 }); },
    notes(A, big) { const s = '♪♫♬♩'; for (let i = 0; i < n(big ? 26 : 10); i++) later(i * 45, () => { const x0 = A.f.x + R(-40, 40), y0 = A.f.y + R(-80, 20), tx = A.t.x + R(-60, 60), ty = A.t.y + R(-80, 40), ch = s[(Math.random() * 4) | 0], col = ['#ff8ad8', '#8fd8ff', '#ffe08a'][(Math.random() * 3) | 0];
      add({ add: true, life: .9, draw(c, k) { const x = x0 + (tx - x0) * k, y = y0 + (ty - y0) * k - Math.sin(k * Math.PI) * 60; c.globalAlpha = fade(k, .1, .8); c.fillStyle = col; c.shadowColor = col; c.shadowBlur = 14; c.font = '900 34px serif'; c.textAlign = 'center'; c.fillText(ch, x, y); } }); }); },
    waterfist(A, big) { P().wave(A.f.x, A.t.x, A.t.y + 40, { h: big ? 220 : 130, life: .7 }); fly(A, (c) => { const g = c.createRadialGradient(0, 0, 0, 0, 0, 50); g.addColorStop(0, '#fff'); g.addColorStop(.4, '#8fd8ff'); g.addColorStop(1, 'rgba(0,0,0,0)'); c.fillStyle = g; c.beginPath(); c.arc(0, 0, big ? 70 : 46, 0, TAU); c.fill(); }, { life: .4 }); },
    fist(A, big) { fly(A, (c, k) => { c.save(); c.scale(1 + k, 1 + k); fist(c, big ? 30 : 20, '#e8b88a'); c.restore(); }, { life: .3, add: false }); },
    axe(A, big) { P().slash(A.t.x, A.t.y, { r: big ? 220 : 150, a: -2.8, span: 2.6, color: '#d0d8e8', w: 30, life: .4 }); },
    meteor(A, big) { for (let i = 0; i < (big ? 9 : 3); i++) later(i * 110, () => { const x = A.t.x + R(-90, 90); add({ add: true, life: .45, draw(c, k) { const y = -120 + (A.t.y + 120) * k * k, xx = x + (A.t.x - x) * k; c.globalAlpha = 1; const g = c.createLinearGradient(xx, y - 120, xx, y); g.addColorStop(0, 'rgba(255,120,40,0)'); g.addColorStop(1, '#ffd08a'); c.strokeStyle = g; c.lineWidth = 14; c.beginPath(); c.moveTo(xx - 30, y - 120); c.lineTo(xx, y); c.stroke(); c.fillStyle = '#5a4030'; c.beginPath(); c.arc(xx, y, 22, 0, TAU); c.fill(); } }); later(430, () => P().burst(x, A.t.y, { color: '#ffaa5a', r: 90 })); }); },
    magma(A, big) { fly(A, (c, k) => { const s = (big ? 90 : 50) * (1 + k * .5); const g = c.createRadialGradient(0, 0, 0, 0, 0, s); g.addColorStop(0, '#fff2a0'); g.addColorStop(.4, '#ff6a1a'); g.addColorStop(.8, '#8a1000'); g.addColorStop(1, 'rgba(0,0,0,0)'); c.fillStyle = g; c.beginPath(); c.arc(0, 0, s, 0, TAU); c.fill(); }, { life: .5 }); later(450, () => P().flames(A.t.x, A.t.y, { n: big ? 70 : 30 })); },
    icefield(A, big) { add({ add: true, life: 1.2, draw(c, k) { const w = 900 * Math.min(1, k * 2.5); c.globalAlpha = fade(k, .05, .7) * .55; const g = c.createLinearGradient(A.f.x, 0, A.f.x + A.d * w, 0); g.addColorStop(0, '#e8fbff'); g.addColorStop(1, 'rgba(160,230,255,0)'); c.fillStyle = g; c.save(); c.translate(0, A.f.y + 120); c.scale(1, .18); c.fillRect(Math.min(A.f.x, A.f.x + A.d * w), -200, w, 400); c.restore(); } });
      P().spikes && later(250, () => P().spikes(A.t.x, A.t.y + 80, { n: big ? 18 : 8, color: '#bff4ff' })); },
    beams(A, big) { for (let i = 0; i < (big ? 12 : 4); i++) later(i * 60, () => P().beam(A.f.x, A.f.y - R(10, 60), A.t.x + R(-40, 40), A.t.y + R(-60, 40), { c2: '#ffe86f', w: 10, life: .28 })); },
    hydra(A, big) { for (let i = 0; i < (big ? 3 : 1); i++) later(i * 160, () => P().serpent(A.f.x, A.f.y + 40 - i * 40, A.t.x, A.t.y - 20 + i * 30, { body: '#7a3ad8', belly: '#c88aff', eye: '#ffef5a', life: .9, len: 420, w: 40 })); },
    claws(A, big) { P().claws(A.t.x, A.t.y, { color: '#ffe0a0' }); if (big) later(200, () => P().claws(A.t.x, A.t.y, { color: '#ffffff' })); },
    bamboo(A, big) { for (let i = 0; i < (big ? 6 : 3); i++) later(i * 70, () => P().slash(A.t.x + R(-30, 30), A.t.y, { r: 140, a: -1.6, span: .3, color: '#5aff8a', w: 12, life: .25 })); },
    greenslash(A, big) { add({ add: true, life: .6, draw(c, k) { const x = A.f.x + (A.t.x - A.f.x + A.d * 300) * k, h = big ? 520 : 300; c.globalAlpha = fade(k, .05, .7); c.translate(x, A.t.y); c.rotate(.15 * A.d); const g = c.createLinearGradient(-40, 0, 20, 0); g.addColorStop(0, 'rgba(0,0,0,0)'); g.addColorStop(.7, '#3affb0'); g.addColorStop(1, '#ffffff'); c.fillStyle = g; c.beginPath(); c.moveTo(0, -h / 2); c.quadraticCurveTo(40 * A.d, 0, 0, h / 2); c.quadraticCurveTo(10 * A.d, 0, 0, -h / 2); c.fill(); } }); },
    sandspiral(A, big) { P().tornado(A.t.x, A.t.y + 40, { life: big ? 1.4 : .9, smoke: '#d9b064' }); },
    birdcage(A, big) { add({ add: true, life: big ? 1.6 : .9, draw(c, k) { const e = Math.min(1, k * 2), r = big ? 260 : 150; c.globalAlpha = fade(k, .05, .75); c.strokeStyle = '#ffd0f0'; c.shadowColor = '#ff5ad0'; c.shadowBlur = 10; c.lineWidth = 1.5; const cx = A.t.x, cy = A.t.y; for (let i = 0; i < 18; i++) { const a = i / 18 * Math.PI; c.beginPath(); c.ellipse(cx, cy - r * .2, r * Math.abs(Math.cos(a)) + 2, r * e, 0, 0, TAU); c.stroke(); } } }); },
    paws(A, big) { for (let i = 0; i < (big ? 7 : 3); i++) later(i * 90, () => fly({ ...A, t: { x: A.t.x + R(-40, 40), y: A.t.y + R(-50, 40) } }, (c, k) => { c.fillStyle = 'rgba(255,190,120,.9)'; c.beginPath(); c.arc(0, 8, 26, 0, TAU); c.fill(); [[-22, -20], [-8, -30], [8, -30], [22, -20]].forEach(([x, y]) => { c.beginPath(); c.arc(x, y, 9, 0, TAU); c.fill(); }); }, { life: .35 })); },
    bats(A, big) { for (let i = 0; i < n(big ? 30 : 12); i++) later(i * 25, () => { const y0 = A.f.y + R(-100, 40), y1 = A.t.y + R(-80, 60); add({ life: .8, draw(c, k) { const x = A.f.x + (A.t.x - A.f.x) * k, y = y0 + (y1 - y0) * k + Math.sin(k * 20) * 10, f = Math.sin(k * 40) * 10; c.globalAlpha = fade(k, .1, .8); c.fillStyle = '#1a0a2a'; c.beginPath(); c.moveTo(x, y); c.lineTo(x - 18, y - 6 + f); c.lineTo(x - 8, y + 2); c.lineTo(x, y + 6); c.lineTo(x + 8, y + 2); c.lineTo(x + 18, y - 6 + f); c.closePath(); c.fill(); } }); }); },
    room(A, big) { add({ add: true, life: big ? 1.6 : 1, draw(c, k) { const r = (big ? 360 : 240) * Math.min(1, k * 3); c.globalAlpha = fade(k, .05, .8) * .5; c.strokeStyle = '#8fe0ff'; c.lineWidth = 3; c.beginPath(); c.arc((A.f.x + A.t.x) / 2, (A.f.y + A.t.y) / 2, r, 0, TAU); c.stroke(); const g = c.createRadialGradient((A.f.x + A.t.x) / 2, (A.f.y + A.t.y) / 2, r * .7, (A.f.x + A.t.x) / 2, (A.f.y + A.t.y) / 2, r); g.addColorStop(0, 'rgba(120,200,255,0)'); g.addColorStop(1, 'rgba(120,200,255,.35)'); c.fillStyle = g; c.fill(); } });
      later(300, () => P().slash(A.t.x, A.t.y, { r: 200, a: A.d > 0 ? -.3 : -2.8, span: .5, color: '#bff0ff', w: 10, life: .3 })); },
    hearts(A, big) { for (let i = 0; i < n(big ? 34 : 14); i++) later(i * 30, () => { const x0 = A.f.x + R(-30, 30), y0 = A.f.y + R(-60, 20), tx = A.t.x + R(-60, 60), ty = A.t.y + R(-80, 50), s = R(10, 20); add({ add: true, life: .8, draw(c, k) { c.globalAlpha = fade(k, .1, .8); c.translate(x0 + (tx - x0) * k, y0 + (ty - y0) * k); c.rotate(Math.sin(k * 10) * .3); c.fillStyle = '#ff5aa8'; c.shadowColor = '#ff8ad8'; c.shadowBlur = 12; heart(c, s); } }); }); },
    blackhole(A, big) { P().vortex(A.t.x, A.t.y, { r: big ? 200 : 110, color: '#2a0a3a', core: '#000000', rim: '#8a5aff', arms: 6, spin: 10, life: big ? 1.4 : .8 }); },
    firefist(A, big) { fly(A, (c, k) => { const s = big ? 110 : 60; c.save(); c.scale(1 + k * .4, 1 + k * .4); const g = c.createRadialGradient(0, 0, 0, 0, 0, s); g.addColorStop(0, '#fff4c0'); g.addColorStop(.35, '#ffa02e'); g.addColorStop(.8, '#ff3a0a'); g.addColorStop(1, 'rgba(0,0,0,0)'); c.fillStyle = g; c.beginPath(); c.arc(0, 0, s, 0, TAU); c.fill(); fist(c, s * .35, 'rgba(255,240,200,.9)'); c.restore(); }, { life: .5 }); },
    phoenix(A, big) { fwings(A.f.x, A.f.y - 30, ['#e8fbff', '#3ad8ff'], big ? 1.4 : .9, big ? 1.4 : 1); P().flames(A.f.x, A.f.y, { n: big ? 60 : 24, colors: ['#e8fbff', '#5ae0ff', '#2a8aff'] }); },
    pteranodon(A, big) { P().flames(A.f.x, A.f.y, { n: big ? 60 : 24 }); fwings(A.f.x, A.f.y - 30, ['#fff0c0', '#ff6a2a'], .9, big ? 1.3 : 1); },
    mochi(A, big) { for (let i = 0; i < (big ? 8 : 3); i++) later(i * 80, () => fly({ ...A, t: { x: A.t.x, y: A.t.y + R(-50, 40) } }, (c, k) => { c.fillStyle = '#f4e8f0'; c.strokeStyle = '#c8a8c0'; c.lineWidth = 3; c.beginPath(); c.ellipse(0, 0, 34, 28, 0, 0, TAU); c.fill(); c.stroke(); }, { life: .35, add: false })); },
    foxfire(A, big) { for (let i = 0; i < (big ? 9 : 4); i++) later(i * 60, () => fly({ ...A, t: { x: A.t.x + R(-50, 50), y: A.t.y + R(-60, 40) } }, (c) => { const g = c.createRadialGradient(0, 0, 0, 0, 0, 28); g.addColorStop(0, '#ffffff'); g.addColorStop(.4, '#8a5aff'); g.addColorStop(1, 'rgba(0,0,0,0)'); c.fillStyle = g; c.beginPath(); c.arc(0, 0, 28, 0, TAU); c.fill(); }, { life: .5, arc: R(-80, 80) })); },
    kingsaura(A, big) { for (let i = 0; i < (big ? 8 : 3); i++) later(i * 60, () => { const a = R(0, TAU), L = R(120, 300); P().bolt(A.f.x, A.f.y, A.f.x + Math.cos(a) * L, A.f.y + Math.sin(a) * L, { color: Math.random() < .5 ? '#140000' : '#ff2a3a', w: 5, life: .3 }); }); if (big) P().ring(A.f.x, A.f.y, { r1: 600, color: '#ff2a3a', w: 24, life: .7 }); },
    parts(A, big) { for (let i = 0; i < (big ? 10 : 4); i++) later(i * 60, () => fly({ ...A, t: { x: A.t.x + R(-60, 60), y: A.t.y + R(-60, 50) } }, (c, k) => { c.rotate(k * 12); c.fillStyle = '#e8c0a0'; c.fillRect(-14, -6, 28, 12); }, { life: .45, arc: 100, add: false })); },
    crack(A, big) { P().cracks && P().cracks(A.t.x, A.t.y, { n: big ? 18 : 10 }); add({ add: true, life: .7, draw(c, k) { const r = 60 + 300 * k; c.globalAlpha = (1 - k) * .8; c.strokeStyle = '#ffffff'; c.lineWidth = 6; c.beginPath(); c.arc(A.t.x, A.t.y, r, 0, TAU); c.stroke(); c.lineWidth = 2; c.beginPath(); c.arc(A.t.x, A.t.y, r * .8, 0, TAU); c.stroke(); } }); },
    homies(A, big) { fly(A, (c, k) => { const s = big ? 70 : 44; const g = c.createRadialGradient(0, 0, 0, 0, 0, s); g.addColorStop(0, '#fff7c0'); g.addColorStop(.6, '#ff9a2e'); g.addColorStop(1, 'rgba(0,0,0,0)'); c.fillStyle = g; c.beginPath(); c.arc(0, 0, s, 0, TAU); c.fill(); c.fillStyle = '#3a1a0a'; c.beginPath(); c.arc(-12, -8, 5, 0, TAU); c.arc(12, -8, 5, 0, TAU); c.fill(); c.lineWidth = 3; c.strokeStyle = '#3a1a0a'; c.beginPath(); c.arc(0, 4, 12, 0, Math.PI); c.stroke(); }, { life: .55, arc: 60 }); },
    dragon(A, big) { P().serpent(A.f.x - A.d * 160, A.f.y + 40, A.t.x + A.d * 80, A.t.y - 40, { body: '#3f7fe8', belly: '#bfe8ff', eye: '#ff5a5a', horn: true, fins: true, fin: '#e8c170', life: big ? 1.2 : .8, len: big ? 520 : 360, w: big ? 60 : 44 }); },
    clima(A, big) { P().puffs && P().puffs(A.t.x, A.t.y - 190, { n: big ? 12 : 6, rad: big ? 140 : 80, life: .9, color: '#e8f0ff' }); for (let i = 0; i < (big ? 6 : 2); i++) later(160 + i * 110, () => { P().bolt(A.t.x + R(-60, 60), A.t.y - 190, A.t.x + R(-20, 20), A.t.y, { color: i % 2 ? '#8fd8ff' : '#fff3a0', w: 6, life: .28 }); }); },
    drums(A, big) { P().drums && P().drums(A.f.x, A.f.y - 40, { life: 1 }); for (let i = 0; i < (big ? 6 : 2); i++) later(150 + i * 120, () => { P().bolt(A.t.x + R(-60, 60), -40, A.t.x + R(-20, 20), A.t.y, { color: '#ffe86f', w: 6, life: .3 }); P().flash('#fffbd0', .08, .2); }); },
    ghosts(A, big) { for (let i = 0; i < n(big ? 14 : 6); i++) later(i * 60, () => fly({ ...A, t: { x: A.t.x + R(-60, 60), y: A.t.y + R(-80, 40) } }, (c, k) => { c.fillStyle = 'rgba(255,240,255,.85)'; c.beginPath(); c.arc(0, -6, 16, Math.PI, 0); c.lineTo(16, 12); for (let j = 0; j < 4; j++) c.lineTo(12 - j * 8, 6 + (j % 2) * 6); c.closePath(); c.fill(); c.fillStyle = '#000'; c.beginPath(); c.arc(-5, -6, 2.5, 0, TAU); c.arc(5, -6, 2.5, 0, TAU); c.fill(); }, { life: .7, arc: R(-60, 60), add: false })); },
    sharks(A, big) { for (let i = 0; i < (big ? 8 : 3); i++) later(i * 80, () => P().serpent(A.f.x, A.f.y + R(-60, 40), A.t.x, A.t.y + R(-40, 40), { body: '#6f8fa8', belly: '#e8f2f8', eye: '#ffd23b', fins: true, fin: '#8fb0c8', life: .45, len: 220, w: 34 })); },
    seakings(A, big) { for (let i = 0; i < (big ? 3 : 1); i++) later(i * 200, () => P().serpent(A.f.x - A.d * 220, A.f.y + 60 - i * 50, A.t.x, A.t.y - 40 + i * 40, { body: '#2f9f8a', belly: '#c9f5e6', eye: '#ffef5a', fins: true, life: 1, len: 520, w: 56 })); },
    snow(A, big) { P().particles({ x: A.t.x, y: A.t.y - 120, n: big ? 70 : 30, spd: [40, 160], ang: [1.2, 1.9], life: [.8, 1.3], size: [3, 6], colors: ['#ffffff', '#e8fbff'], drag: 1 }); },
    toys(A, big) { for (let i = 0; i < (big ? 6 : 3); i++) later(i * 80, () => P().text(A.t.x + R(-60, 60), A.t.y + R(-60, 30), ['🧸', '🎈', '🪀'][i % 3], { size: 40, life: .7 })); },
    magnet(A, big) { for (let i = 0; i < n(big ? 30 : 12); i++) later(i * 25, () => fly({ ...A, f: { x: A.f.x + R(-120, 120), y: A.f.y + R(-160, 40) } }, (c, k) => { c.rotate(k * 10); c.fillStyle = '#9aa8b8'; c.fillRect(-10, -4, 20, 8); }, { life: .4, add: false })); },
    giantblade(A, big) { add({ add: true, life: .55, draw(c, k) { const a = -2.4 + k * 2.4; c.globalAlpha = fade(k, .05, .7); c.translate(A.t.x - A.d * 60, A.t.y - 200); c.rotate(A.d > 0 ? a : -a); c.fillStyle = '#d8e0f0'; c.shadowColor = '#ffffff'; c.shadowBlur = 20; c.fillRect(-14, 0, 28, big ? 420 : 300); } }); }
  };
  window.addEventListener('DOMContentLoaded', () => {
    if (typeof playChoreo !== 'function') return; const _p = playChoreo;
    window.playChoreo = playChoreo = async function (side, actor, idx, skill) {
      const f = on() && actor && MOTIF[actor.id] && M[MOTIF[actor.id]];
      if (f) { try { const S = side === 'P' ? 'L' : 'R', T = S === 'L' ? 'R' : 'L', A = { S, T, f: fighterPoint(S), t: fighterPoint(T), d: S === 'L' ? 1 : -1 }; const big = !!(skill && skill.ultimate), sup = skill && skill.type === 'support';
        if (sup && !['nika', 'phoenix', 'pteranodon', 'asura', 'kingsaura', 'drums', 'room', 'notes'].includes(MOTIF[actor.id])) { /* 輔助招式：招牌元素繞著自己 */ later(200, () => f({ ...A, t: { x: A.f.x + A.d * 10, y: A.f.y - 60 } }, big)); }
        else later(big ? 900 : 220, () => f(A, big)); } catch (e) { } }
      return _p.apply(this, arguments); };
  });
  window.__MOTIF = M;
})();
